---
# Source: dummy1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dummy1
  labels:
    helm.sh/chart: dummy1-0.1.0
    app.kubernetes.io/name: dummy1
    app.kubernetes.io/instance: app1-dummy1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dummy1
      app.kubernetes.io/instance: app1-dummy1
  template:
    metadata:
      labels:
        helm.sh/chart: dummy1-0.1.0
        app.kubernetes.io/name: dummy1
        app.kubernetes.io/instance: app1-dummy1
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: app1-dummy1
      securityContext:
        {}
      containers:
        - name: dummy1
          securityContext:
            {}
          image: "public.ecr.aws/nginx/nginx:1.29.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
