---
# Source: dummy1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app1-dummy1
  labels:
    helm.sh/chart: dummy1-0.1.0
    app.kubernetes.io/name: dummy1
    app.kubernetes.io/instance: app1-dummy1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dummy1
    app.kubernetes.io/instance: app1-dummy1
